acme_topic:
    channel: acme/channel
    handler:
        callback: 'acme.topic' #related to the getName() of your topic

acme_rpc:
    channel: sample/sum
    handler:
        callback: 'acme.rpc' #related to the getName() or your RPC service